# Setup
title:               더누림 기록
tagline:             'THENURIM Logs'
# description:         'Reserved by <a href="https://thenurim.life" target="_blank">더누림</a>'
description:         'THENURIM Business Logs'
url:                 https://blog.thenurim.life
baseurl:             ''
permalink:           pretty
# github:            https://github.com/thenurim

# Language-based post defaults
defaults:
  - scope:
      path: "_posts/en"
      type: posts
    values:
      lang: en
      permalink: /en/:year/:month/:day/:title/
  - scope:
      path: "_posts/ko"
      type: posts
    values:
      lang: ko
      permalink: /ko/:year/:month/:day/:title/

# About/contact
author:
  name:              THENURIM
  url:               https://novalink.thenurim.life
  email:             ceo@thenurim.life

# Gems
plugins: []

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

comments: true
