# Setup
title:               더누림 로그
tagline:             'THENURIM Logs'
description:         'A reserved by <a href="https://thenurim.life" target="_blank">더누림</a>'
url:                 https://blog.thenurim.life
baseurl:             ''
paginate:            1
permalink:           pretty
# github:            https://github.com/thenurim

# About/contact
author:
  name:              THENURIM
  url:               https://novalink.thenurim.life
  email:             ceo@thenurim.life

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

comments: true
