# Setup
title:               더누림 성장 일지
tagline:             'TheNurim Growth Log'
description:         'A reserved by <a href="https://thenurim.github.io" target="_blank">더누림</a>'
url:                 https://thenurim.github.io
baseurl:             ''
paginate:            1
permalink:           pretty
github:            https://github.com/thenurim

# About/contact
author:
  name:              TheNurim
  url:               https://thenurim.github.io
  email:             ceo@thenurim.life

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

comments: true
